[package]
name = "snippets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util="0.3.11"
crossbeam="0.8.1"
itertools = "0.10.2"
rand = "0.8.5"